inherit_gem:
  gc_ruboconfig: rubocop.yml

AllCops:
  Exclude: [legacy_spec/**/*]

Metrics/MethodLength:
  Max: 20

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10
