---
version: 2
jobs:
  build:
    working_directory: ~/que
    docker:
      - image: ruby:2.4.2
        environment:
          PGDATABASE: que-test
          PGUSER: ubuntu
          PGPASSWORD: password
          PGHOST: localhost
      - image: postgres:9.4.17
        environment:
          POSTGRES_DB: que-test
          POSTGRES_USER: ubuntu
          POSTGRES_PASSWORD: password
    steps:
      - checkout
      - restore_cache:
          key: gemfile-{{ .Branch }}-{{ checksum "Gemfile" }}
      - run: bundle install
      - save_cache:
          key: gemfile-{{ .Branch }}-{{ checksum "Gemfile" }}
          paths:
            - "vendor/bundle"
      - run: bundle exec rspec
